//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Konec
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип вольера.
    /// </summary>
    // *** Start programmer edit section *** (ТипВольера CustomAttributes)

    // *** End programmer edit section *** (ТипВольера CustomAttributes)
    public enum ТипВольера
    {
        
        // *** Start programmer edit section *** (ТипВольера.ДляКрупныхЖивотных CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.ДляКрупныхЖивотных CustomAttributes)
        [Caption("Для крупных животных")]
        ДляКрупныхЖивотных,
        
        // *** Start programmer edit section *** (ТипВольера.ДляПтиц CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.ДляПтиц CustomAttributes)
        [Caption("Для птиц")]
        ДляПтиц,
        
        // *** Start programmer edit section *** (ТипВольера.Аквариум CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Аквариум CustomAttributes)
        [Caption("Аквариум")]
        Аквариум,
        
        // *** Start programmer edit section *** (ТипВольера.Терариум CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Терариум CustomAttributes)
        [Caption("Терариум")]
        Терариум,
        
        // *** Start programmer edit section *** (ТипВольера.Экзотический CustomAttributes)

        // *** End programmer edit section *** (ТипВольера.Экзотический CustomAttributes)
        [Caption("Экзотический")]
        Экзотический,
    }
}
